language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
  - wget http://downloads.sourceforge.net/project/boost/boost/1.55.0/boost_1_55_0.tar.bz2
  - tar -xjf boost_1_55_0.tar.bz2
  - BOOST_PATH=`pwd`/boost_1_55_0
  - export BOOST_PATH
install:
#   - pip install coveralls
  - python setup.py install
script:
  - python test_orderedset.py
#   - coverage run setup.py test
#   - coverage report
# after_script:
#   coveralls --verbose
